force-app/main/default/objects/Beer__c/Beer__c.object-meta.xml
<CustomObject>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beer__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Id retrieved from Punk API.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BeerAPICalloutTest.cls
@isTest
private class BeerAPICalloutTest {
    
    @testSetup
    static void setup() {
        // Create and insert a Beer__c item
        Beer__c testBeer = new Beer__c();
        testBeer.External_ID__c = 1;
        testBeer.Name = 'Buzz';
        
        insert testBeer;
    }
    
    @isTest 
    static  void testGetCallout() {
        // Create the mock response based on a static resource
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetBeerResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);
        
        // Call method to test
		Test.startTest();
        BeerAPICallout.makeGetCallout();        
        Test.stopTest();
        
        // Check results
        List<Beer__c> results = [SELECT Name FROM Beer__c];
		System.assertEquals(2, results.size(), 'The array should only contain 2 items.');
        System.assertEquals('Buzz', results[0].Name, 'The name of the beer does not match.');

    }   
}